spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/campus_buddy?useUnicode=true&characterEncoding=utf8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  # 启用静态资源映射，允许访问测试页面
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
      chain:
        enabled: true
      cache:
        period: 0
  mvc:
    problemdetails:
      enabled: false
    favicon:
      enabled: false  # 禁用 Spring 的 favicon 处理，使用自定义的
  websocket:
    config:
      allowedOrigins: '*'  # 允许的 WebSocket 来源，生产环境中应当限制

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.example.campusbuddy.entity
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰命名
  configuration-properties:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

qiniu:
  access-key: ${QINIU_ACCESS_KEY:your_access_key_here}
  secret-key: ${QINIU_SECRET_KEY:your_secret_key_here}
  bucket: ${QINIU_BUCKET:campus-buddy-platform}
  domain: ${QINIU_DOMAIN:http://example.domain.com} # 从环境变量获取七牛云空间外链域名
