spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_buddy?useUnicode=true&characterEncoding=utf8
    username: night
    password: 123
  redis:
    host: localhost
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
