spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_buddy?useUnicode=true&characterEncoding=utf8
    username: night
    password: 123
  redis:
    host: localhost
    port: 6379
  # 禁用全局异常处理注解与Swagger冲突
  mvc:
    problemdetails:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.example.campusbuddy.entity
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰命名
  configuration-properties:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# 文件上传配置
file:
  upload:
    path: ${user.dir}/tmp/uploads

qiniu:
  access-key: 5bELhkZ5FX4vGjdfH5S9OwTDghKkLQ-IGZSwhduG
  secret-key: OOCCkj59LkxH13V9b1DNjq_s_Y6mwqIdhi4GPaOi
  bucket: campus-buddy-platform
  domain: http://swpyovvlr.hn-bkt.clouddn.com # 请替换为你的七牛云空间外链域名
